Wip hyperledger fabric monitoring
centreon/centreon-plugins pull request #2530
Opened 2021-01-20 14:12 UTC by zaouchelo

This PR aim to add Hyperledger Fabric plugins

2021-01-20 14:25 UTC, Sims24 requested changes
H @zaouchelo 

Please clean the code and remove all dumper and commented code. 

Also, you are modifying some common mode like openmetrics one, it's a problem because it breaks existing stuff.

2021-01-20 14:26 UTC, Sims24 commented
Or maybe you can convert your PR as draft ;)

2021-03-11 13:17 UTC, Sims24 commented
@zaouchelo please provide update on the status and/or ETA of a ready to review PR. 

Also, if you can provide more privately an environment to test the Plugin it would be awesome.

2021-03-11 15:00 UTC, zaouchelo commented
@Sims24 Sorry I was busy with other stuff... I planned to work on it early next week.
Yes, I'll share with you the test environment.

2021-12-01 10:53 UTC, Sims24 commented on blockchain/hyperledger/exporter/ledger/mode/metrics.pm
> +sub prefix_output_leger {
typo missing 'd'

2022-03-24 08:28 UTC, Sims24 commented
Won't merge. Expiring.

2022-03-24 08:28 UTC, closed without merging