Add proper TCP responsetime mode
centreon/centreon-plugins pull request #2709
Opened 2021-04-15 12:44 UTC by UrBnW

Hi,

This PR adds a proper TCP `responsetime` mode which mimics :
- `check_icmp` binary ;
- `apps::protocols::snmp::mode::responsetime` mode.

The main purpose of this new TCP `responsetime` mode is to be used as a host check, when `check_icmp` can't be used.
Think about for example of a Windows host (with NSClient++) behind a router / firewall.
This new TCP `responsetime` mode will then allow to check the availability of host, computing proper already known `rta` / `rtmin` / `rtmax` / `pl` perfdata.

Current `apps::protocols::tcp::mode::responsetime` mode has then been renamed to a more appropriated `apps::protocols::tcp::mode::connectionstatus` mode.

Many thx 👍

2021-04-15 12:45 UTC, UrBnW commented
```
# centreon_plugins.pl --plugin=apps::protocols::tcp::plugin --mode=response-time --hostname=google.com --port=80  
OK: TCP port 80 rta 9.529ms, lost 0% | 'rta'=9.529ms;;;0; 'rtmax'=10.925ms;;;0; 'rtmin'=8.965ms;;;0; 'pl'=0%;;;0;100
```

2021-05-24 12:41 UTC, Sims24 requested changes
Few things that need to be done. 

I agree it's a good idea to have a much detailed tcp ping, nevertheless renaming modes require some changes on the Plugin Pack packaging and it will take some time to merge it and avoid breaking existing setup.

2021-05-24 12:41 UTC, Sims24 commented on apps/protocols/tcp/mode/responsetime.pm
> +    }
You should use the following syntax to define a default value for options: 

```
        'timeout:s'  => { name => 'timeout' , default => 5},
        'packets:s'  => { name => 'packets' , default => 5},
```

2021-05-24 12:41 UTC, Sims24 commented on apps/protocols/tcp/mode/responsetime.pm
>      }
You can simply check that an option is defined and not empty. You can of course check that's an integer but we don't got this far most of the time ...

2021-05-24 12:41 UTC, Sims24 commented on apps/protocols/tcp/mode/responsetime.pm
> -            Timeout => $self->{option_results}->{timeout},
Better to keep the common way of accessing value option IMHO

2021-05-26 19:58 UTC, UrBnW commented
Many thanks for your review @Sims24, all points addressed in last commit !

2022-03-24 08:29 UTC, Sims24 approved these changes

2022-03-24 08:59 UTC, UrBnW commented
Many thanks @Sims24 👍

2022-05-19 06:36 UTC, merged

2022-06-08 15:10 UTC, UrBnW commented
Thank you very much @garnier-quentin ;)