new mode "capacity" for Azure APIM
centreon/centreon-plugins pull request #2803
Opened 2021-05-18 09:33 UTC by matoy

gives the percentage of used capacity of the APIM

[root@svzam-cenpol001 apimanagement]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::management::apimanagement::plugin --custommode='api' --mode='capacity' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-capacity-percentage='80' --critical-capacity-percentage='90'
OK: Instance 'xxx' Statistic 'average' Metrics Capacity: 2.46% | 'xxx#apimanagement.capacity.percentage'=2.46%;0:80;0:90;0;

2021-05-18 10:28 UTC, itoussies requested changes
Hi @matoy,

Thanks for the PR ! Here are some details to change

2021-05-18 10:28 UTC, itoussies commented on cloud/azure/management/apimanagement/mode/capacity.pm
> +Default aggregation: 'total' / 'average', 'minimum' and 'maximum' are valid.
```suggestion
Default aggregation: 'average' / 'total', 'minimum' and 'maximum' are valid.
```

2021-05-18 10:28 UTC, itoussies commented on cloud/azure/management/apimanagement/mode/capacity.pm
> +'capacity-percentage'.
```suggestion
=item B<--warning-capacity-percentage>

Set warning threshold for capacity.
```

2021-05-18 10:28 UTC, itoussies commented on cloud/azure/management/apimanagement/mode/capacity.pm
> +'capacity-percentage'.
```suggestion
=item B<--critical-capacity-percentage>

Set critical threshold for capacity.
```

2021-05-18 10:35 UTC, itoussies requested changes

2021-05-18 10:35 UTC, itoussies commented on cloud/azure/management/apimanagement/mode/capacity.pm
> +        },
```suggestion
            'min'    => '0',
            'max'    => '100',
        },
```

2021-05-18 12:02 UTC, itoussies approved these changes

2021-05-18 12:03 UTC, itoussies commented
Thank you !

2021-05-18 14:43 UTC, Sims24 commented
@matoy any reason why you closed this one? Maybe you've mistaken with https://github.com/centreon/centreon-plugins/pull/2802

2021-05-18 15:21 UTC, matoy commented
mistake from my part, indeed.

2021-05-18 15:59 UTC, Sims24 commented
Thanks! As we will release officially Plugins and Packs tomorrow, we will merge this at the end of this week or next week. 

@itoussies committed a part of the patch you offered here: #2802 . About the other fix related to metric_mapping, we need to dig around with you cause we don't understand why we don't get the same behavior.

2021-05-21 09:33 UTC, Sims24 commented
Thank you!

2021-05-21 09:33 UTC, merged