new plugin for Azure Redis Cache with 10 modes + discovery
centreon/centreon-plugins pull request #2808
Opened 2021-05-19 12:19 UTC by matoy

[root@svzam-cenpol001 mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --list-mode

Plugin Description:
    Check Microsoft Azure Redis Cache service.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

    --custommode
            Choose a custom mode.

    --list-custommode
            List available custom modes.

    --multiple
            Multiple custom mode objects (required by some specific modes)

    --pass-manager
            Use a password manager.

Modes Meta:
   multi

Modes Available:
   cache-hits
   cache-latency
   cache-miss-rate
   cache-throughput
   connected-clients
   cpu
   discovery
   errors
   memory
   operations
   server-load

[xxx redis]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='discovery' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx'
{"end_time":1621416611,"start_time":1621416611,"duration":0,"discovered_items":1,"results":[{"location":"westeurope","name":"xxx","resourceGroup":"xxx","type":"Microsoft.Cache/Redis","id":"/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Cache/Redis/xxx","tags":[]}]}

[xxx mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='cache-hits' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-cache-misses='800' --critical-cache-misses='900'
OK: Instance 'xxx' Statistic 'total' Metrics Cache Misses: 426.00, Cache Hits: 494.00 | 'xxx~total#redis.cache.misses.count'=426.00;0:800;0:900;0; 'xxx~total#redis.cache.hits.count'=494.00;;;0;

[xxx mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='cache-latency' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='cdc-abcdior-redis-eu-dev' --warning-cache-latency='8000' --critical-cache-latency='9000'
OK: Instance 'cdc-abcdior-redis-eu-dev' Statistic 'average' Metrics Cache Latency: 2190.66μs | 'cdc-abcdior-redis-eu-dev~average#redis.cache.latency.microseconds'=2190.66μs;0:8000;0:9000;0;

xxx mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='cache-miss-rate' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-cache-miss-rate='40' --critical-cache-miss-rate='50'
OK: Instance 'xxx' Statistic 'average' Metrics Cache Miss Rate: 14.00% | 'xxx~average#redis.cache.miss.rate'=14.00%;0:40;0:50;0;100

[xxx mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='connected-clients' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-connected-clients='800' --critical-connected-clients='900'
OK: Instance 'xxx' Statistic 'average' Metrics Connected Clients: 25.90 | 'xxx~average#redis.cache.connected.clients.count'=25.90;0:800;0:900;0;

[xxx mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='server-load' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-server-load-percentage='80' --critical-server-load-percentage='90'
OK: Instance 'xxx' Statistic 'maximum' Metrics Server Load: 1.00% | 'xxx~maximum#redis.cache.server-load'=1.00%;0:80;0:90;0;100

[xxx mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='operations' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-operations-per-second='80' --critical-operations-per-second='90'
OK: Instance 'xxx' Statistic 'maximum' Metrics Operations per seconds: 8.80op/s | 'xxx~average#redis.cache.operations.persecond'=8.80op/s;0:80;0:90;0;

[xxx mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='cpu' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-cpu-usage-percentage='80' --critical-cpu-usage-percentage='90'
OK: Instance 'xxx' Statistic 'maximum' Metrics CPU Usage Percentage: 13.00% | 'xxx~maximum#redis.cache.cpu.usage.percentage'=13.00%;0:80;0:90;0;100

[xxx mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='memory' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-memory-usage-percentage='80' --critical-memory-usage-percentage='90'
OK: Instance 'xxx' Statistic 'maximum' Metrics Memory Usage Percentage: 1.00% | 'xxx~maximum#redis.cache.memory.usage.percentage'=1.00%;0:80;0:90;0;100

[xxx mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='errors' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --critical-errors-count='1'
OK: Instance 'xxx' Statistic 'total' Metrics Errors: 0.00 | 'xxx~total#redis.cache.errors.count'=0.00;;;0;

[xxx mode]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::database::redis::plugin --custommode='api' --mode='cache-throughput' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-cache-read-throughput='800000' --critical-cache-read-throughput='900000'
OK: Instance 'xxx' Statistic 'maximum' Metrics Cache Read Throughput: 352527.00B/s, Cache Write Throughput: 133482.00B/s | 'xxx~maximum#redis.cache.read.throughput'=352527.00B/s;0:800000;0:900000;0; 'xxx~maximum#redis.cache.write.throughput'=133482.00B/s;;;0;

2021-05-19 15:53 UTC, thibaults-centreon commented
Hello @matoy thank you for this great PR!
could you please merge the 3 following modes: 
cache-hits
cache-latency
cache-miss-rate
in one ('cache-usage' for example) ? From what I see these metrics share the same calculation method so they can be fetched at once.

Afterwards, I'll probably take a deeper look in order to also include the 'redisEntreprise' types in the same Plugin (https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcacheredisenterprise).

2021-05-19 16:07 UTC, matoy commented
i don't think graphs would be easily readable because numbers are in very different scales:
hits are "count" / aggregated: total
latency is in "μs" / aggregated: avg
miss-rate is a "%" /aggregated: avg

2021-06-01 07:49 UTC, thibaults-centreon commented
Ok, I would propose this:
- rename "cachehits" to cacheusage
- discard the miss rate mode for now as the MS documentation about the stats for this metric is wrong (in https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcacheredis)
- rename "connectedtclients" to "clients"
- rename "serverload" to "load"

Aditionnally, some labels need to be adjusted, see comments in code

Thanks!

2021-06-01 08:04 UTC, thibaults-centreon requested changes

2021-06-01 08:04 UTC, thibaults-centreon commented on cloud/azure/database/redis/mode/serverload.pm
> +'server-load-percentage'.
```suggestion
=item B<--warning-server-load-percentage>

Warning threshold.

=item B<--critical-server-load-percentage>

Critical threshold.
```

2021-06-01 08:04 UTC, thibaults-centreon commented on cloud/azure/database/redis/plugin.pm
> +        'cache-throughput'   => 'cloud::azure::database::redis::mode::cachethroughput'
Sort & align please
Also please rename the modes as discussed in the main conversation ;)
Thanks!

2021-06-01 08:04 UTC, thibaults-centreon commented on cloud/azure/database/redis/mode/cachehits.pm
> +Check Azure Redis Cache hits/misses.
```suggestion
Check Azure Redis cache usage statistics.
```

2021-06-01 08:04 UTC, thibaults-centreon commented on cloud/azure/database/redis/mode/cachelatency.pm
> +Check Azure Redis Cache latency.
```suggestion
Check Azure Redis cache latency statistics.
```

2021-06-01 08:04 UTC, thibaults-centreon commented on cloud/azure/database/redis/mode/cachethroughput.pm
> +Check Azure Redis Cache read/write throughput.
```suggestion
Check Azure Redis cache throughput statistics.
```

2021-06-01 08:04 UTC, thibaults-centreon commented on cloud/azure/database/redis/mode/connectedclients.pm
> +Check Azure Redis Cache connected clients.
```suggestion
Check Azure Redis clients statistics.
```

2021-06-01 08:04 UTC, thibaults-centreon commented on cloud/azure/database/redis/mode/cpu.pm
> +Check Azure Redis Cache CPU usage.
```suggestion
Check Azure Redis CPU usage statistics.
```

2021-06-01 08:04 UTC, thibaults-centreon commented on cloud/azure/database/redis/mode/errors.pm
> +Check Azure Redis Cache errors.
```suggestion
Check Azure Redis errors statistics.
```

2021-06-01 08:04 UTC, thibaults-centreon commented on cloud/azure/database/redis/mode/memory.pm
> +Check Azure Redis Cache memory usage.
```suggestion
Check Azure Redis memory statistics.
```

2021-06-01 08:04 UTC, thibaults-centreon commented on cloud/azure/database/redis/mode/serverload.pm
> +Check Azure Redis Cache server load.
```suggestion
Check Azure Redis server load statistics.
```

2021-06-01 16:21 UTC, matoy commented
i agreed all.

2021-06-04 09:47 UTC, thibaults-centreon commented
Hello, changes related to my last comment have ben commited. I also added the "Health" mode that has been successfully tested. We're now good to go! Thanks for your contribution !

2021-06-04 09:47 UTC, thibaults-centreon approved these changes

2021-06-08 07:05 UTC, merged