new feature: azure traffic manager
centreon/centreon-plugins pull request #3446
Opened 2022-01-31 14:27 UTC by matoy

2022-02-07 14:58 UTC, Sims24 requested changes
Thanks once again @matoy few things to change to merge this one.

2022-02-07 14:58 UTC, Sims24 commented on cloud/azure/network/trafficmanager/mode/queries.pm
> +            'nlabel' => 'trafficmanager.queries.persecond.count',
persecond is enough, we usually don't use both.

2022-02-07 20:21 UTC, matoy commented
done!

2022-02-09 14:18 UTC, Sims24 commented
Thank you!

2022-02-09 14:39 UTC, Sims24 commented
@matoy one last thing, I checked aggregation Microsoft highlights for those metrics and I see that you use Average instead 
![image](https://user-images.githubusercontent.com/12429463/153223617-2321795e-1591-40cb-b987-c453265eb8b1.png)

Any reason for that?

2022-02-09 20:54 UTC, matoy commented
no ; just a mistake.
actually average, min ou max would no change the result very much. but total should not be used (works but no interest in this value).

2022-02-10 21:07 UTC, Sims24 approved these changes

2022-03-09 08:44 UTC, merged