(plugin) network::fortinet::fortimail::snmp - new
centreon/centreon-plugins pull request #4484
Opened 2023-06-14 13:58 UTC by garnier-quentin

2023-06-16 14:56 UTC, itoussies requested changes

2023-06-16 14:56 UTC, itoussies commented on src/network/fortinet/fortimail/snmp/mode/ha.pm
> +Can used special variables like: %{ha_status}, %{ha_status_last}
```suggestion
You can use the following variables: %{ha_status}, %{ha_status_last}
```

2023-06-16 14:56 UTC, itoussies commented on src/network/fortinet/fortimail/snmp/mode/ha.pm
> +Can used special variables like: %{ha_status}, %{ha_status_last}
```suggestion
You can use the following variables: %{ha_status}, %{ha_status_last}
```

2023-06-16 14:56 UTC, itoussies commented on src/network/fortinet/fortimail/snmp/mode/interfaces.pm
> +Can used special variables like: %{admstatus}, %{opstatus}, %{duplexstatus}, %{display}
```suggestion
You can use the following variables: %{admstatus}, %{opstatus}, %{duplexstatus}, %{display}
```

2023-06-16 14:56 UTC, itoussies commented on src/network/fortinet/fortimail/snmp/mode/interfaces.pm
> +Can used special variables like: %{admstatus}, %{opstatus}, %{duplexstatus}, %{display}
```suggestion
You can use the following variables: %{admstatus}, %{opstatus}, %{duplexstatus}, %{display}
```

2023-06-16 14:59 UTC, itoussies submitted a review, later dismissed

2023-07-04 15:03 UTC, sdepassio approved these changes

2023-07-05 08:14 UTC, itoussies approved these changes

2023-07-05 08:14 UTC, merged