(plugin) network::chapsvision::crossing::snmp - new
centreon/centreon-plugins pull request #4582
Opened 2023-07-27 12:54 UTC by garnier-quentin

2023-08-08 14:40 UTC, sdepassio submitted a review, later dismissed

2023-08-29 15:43 UTC, omercier requested changes

2023-08-29 15:43 UTC, omercier commented on src/network/chapsvision/crossing/snmp/mode/antivirus.pm
> +Define the conditions to match for the version to be UNKNOWN.
```suggestion
Define the conditions the version must match for the status to be UNKNOWN.
```

2023-08-29 15:43 UTC, omercier commented on src/network/chapsvision/crossing/snmp/mode/antivirus.pm
> +Define the conditions to match for the version to be WARNING.
```suggestion
Define the conditions the version must match for the status to be WARNING.
```

2023-08-29 15:43 UTC, omercier commented on src/network/chapsvision/crossing/snmp/mode/antivirus.pm
> +Define the conditions to match for the version to be CRITICAL.
```suggestion
Define the conditions the version must match for the status to be CRITICAL.
```

2023-09-27 14:00 UTC, lucie-dubrunfaut approved these changes

2023-11-06 09:39 UTC, omercier approved these changes

2023-11-13 09:16 UTC, merged