Check fortiauthentificator with api
centreon/centreon-plugins pull request #4801
Opened 2024-01-04 08:25 UTC by chris-mvila

## Check Fortitokens with API

Hello, 

We made a fortiauthentificator plugin to monitor fortitokens by API

**The output of plugin :**  
./centreon_plugins.pl --plugin=network::fortinet::fortiauthenticator::restapi::plugin --mode=fortitoken --hostname='xxxxxxx' --port='443' --proto='https' --api-token='xxxxxxx' --api-username=xxxxxx --warning-tokens-usage-prct=90 --critical-tokens-usage-prct=95
OK: [tokens ftm] populated:1690 - used:1478(87.46%) - available:212(12.54%) | 'fortitokens.ftm.tokens.usage.percentage'=87%;0:90;0:95;0;100

**Link of API :**
https://docs.fortinet.com/document/fortiauthenticator/6.1.2/rest-api-solution-guide/875895/fortitokens-fortitokens

You will find : 
- [ ] api.pm 
- [ ] plugin.pm 
- [ ] fotitokens.pm 

Sincerely, 
Chris MVILA

2024-03-07 14:43 UTC, cgagnaire requested changes
The plugin is good but maybe too oriented to your use case.
I'd recommend a wider view.
The vi swap file is too much anyway.

2024-03-07 14:43 UTC, cgagnaire commented on src/network/fortinet/fortiauthenticator/restapi/custom/api.pm
> +    );
```suggestion
    my $content = $self->{http}->request(
        url_path => $options{endpoint},
        unknown_status => $self->{unknown_http_status},
        warning_status => $self->{warning_http_status},
        critical_status => $self->{critical_http_status},
        credentials => 1,
        basic => 1,
        insecure => 1,
        username => $self->{api_username},
        password => $self->{api_token}
    );
```

2024-03-07 14:43 UTC, cgagnaire commented on src/network/fortinet/fortiauthenticator/restapi/custom/api.pm
> +        });
Either align values or just put them one space appart from keys

2024-03-07 14:43 UTC, cgagnaire commented on src/network/fortinet/fortiauthenticator/restapi/custom/api.pm
> +
Some blank lines are too much

2024-03-07 14:43 UTC, cgagnaire commented on src/network/fortinet/fortiauthenticator/restapi/custom/api.pm
> +	$self->{hostname} = (defined($self->{option_results}->{hostname})) ? $self->{option_results}->{hostname} : '';
Use 4 spaces indent and not tabs

2024-03-07 14:43 UTC, cgagnaire commented on src/network/fortinet/fortiauthenticator/restapi/mode/fortitokens.pm
> +        label => 'fortitokens.ftm.tokens.usage.percentage',
```suggestion
        label => 'fortitokens.tokens.ftm.usage.percentage', 
```

2024-03-07 14:43 UTC, cgagnaire commented on src/network/fortinet/fortiauthenticator/restapi/mode/fortitokens.pm
> +    return sprintf("[tokens ftm] populated:%s - used:%s(%.2f%%) - available:%s(%.2f%%)",
```suggestion
    return sprintf("FRM tokens populated: %s, used: %s (%.2f%%), available: %s (%.2f%%)",
```

2024-03-07 14:43 UTC, cgagnaire commented on src/network/fortinet/fortiauthenticator/restapi/plugin.pm
> +        'fortitoken'       => 'network::fortinet::fortiauthenticator::restapi::mode::fortitokens',
```suggestion
        'fortitoken' => 'network::fortinet::fortiauthenticator::restapi::mode::fortitokens',
```

2024-03-07 14:43 UTC, cgagnaire commented on src/network/fortinet/fortiauthenticator/restapi/mode/fortitokens.pm
> +   }
Counters should be initialized to 0.
Testing emptiness at the end doesn't look good to me.
And ultimately you're deciding that used tokens are those which are not available but from the documentation I see statuses like "new", "pending" or "assigned", so I think we should leverage all those statuses and put them into counters, and maybe create an "available percentage" counter for threshold purpose (opposite of used in a sens so it'll work for your use case).
And what about the FTK tokens ?
Maybe if you could privately provide an API output I could propose a version for you to test.

2024-03-26 10:44 UTC, chris-mvila commented
Hi, 
Thank you for your feedback. 
The FortiAuthenticator API is peculiar. 
According to the publisher's documentation, the path /api/v1/fortitokens/ returns all FortiTokens.
This is true, however to determine the number of FortiTokens for each status (available, pending, assigned, ...), you need to parse the information returned by the API and count the number of FortiTokens for each status, considering that the API only returns 1000 by default.

Another way to obtain the number of FortiTokens for each status is to directly retrieve the information for that status.
In this case, there is no need to parse the information because the total_count field contains the number of FortiTokens for the desired status.

I am sending you the results of the command lines below : 
Retrieve all Fortitokens : 
curl -k -v -u "xxxxxx:xxxxxxxxxxxxxxxx" "https://xxxxxxxxx/api/v1/fortitokens/?format=json&limit=10000"  (file : fortiauthen_all.json)
Retrieve available Fortitokens : 
curl -k -v -u "xxxxxx:xxxxxxxxxxxxxxxx" "https://xxxxxxxxx/api/v1/fortitokens/?format=json&limit=10000&status=available" (file : fortiauthen_available.json)
Retrieve assigned Fortitokens 
curl -k -v -u "xxxxxx:xxxxxxxxxxxxxxxx" "https://xxxxxxxxx/api/v1/fortitokens/?format=json&limit=10000&status=assigned" (file : fortiauthen_assigned.json) 

Feel free to ask if you need any further information.

[fortiauthen_all.json](https://github.com/centreon/centreon-plugins/files/14757064/fortiauthen_all.json)
[fortiauthen_assigned.json](https://github.com/centreon/centreon-plugins/files/14757066/fortiauthen_assigned.json)
[fortiauthen_available.json](https://github.com/centreon/centreon-plugins/files/14757067/fortiauthen_available.json)

2024-03-26 11:22 UTC, cgagnaire commented
Hi @chris-mvila,
Thanks for your answer and the material, you can delete the files from your post.
Actually that is not peculiar, this is pagination. And your custom mode must handle it by following the URL in the $.meta.next entry. That way you can add-up results and have all the entries. Then your code can parse the result and fill the counters.
I'll show you how if I have time this week. You can look at https://github.com/centreon/centreon-plugins/blob/444066f78adc966a7fc79cfd62db8cdd8a707725/src/cloud/google/gcp/custom/api.pm#L379 or https://github.com/centreon/centreon-plugins/blob/444066f78adc966a7fc79cfd62db8cdd8a707725/src/cloud/kubernetes/custom/api.pm#L166 if you want to have a try. This case will be different though because its all about URLs.

2024-08-05 14:27 UTC, chris-mvila commented
Hi @lucie-dubrunfaut
We have updated the code for the api.pm module as well as the fortitokens.pm module. 
The plugin is no longer specific as it was before.

Here is what the plugin returns:
./centreon_plugins.pl --plugin=network::fortinet::fortiauthenticator::restapi::plugin --mode=fortitoken --hostname=xxxxx --port=443 --proto=https --api-token='xxxxxx' --api-username=xxxxx  --verbose --insecure --curl-opt="CURLOPT_SSL_VERIFYPEER => 0" --filter-type=ftm
OK: [Tokens] total:1785 - assigned:1669(93.50%) - available:44(2.46%) - pending:72(2.46%) | 'tokens.assigned.percentage'=93%;;;0;100

I remain at your disposal for any further information.

2024-10-28 10:42 UTC, chris-mvila commented
Hello, could you please provide me with feedback regarding this contribution? Thank you in advance.

2024-11-04 11:14 UTC, lucie-dubrunfaut commented
Hello :)

I don't know why it was asked to remove the data needed to test this RP, but in order to integrate this work we will need the output data (anonymized) from the curls commands proposed above (if necessary, you can send them to me by e-mail). 
Thanks again for your contribution :)

2025-07-09 11:55 UTC, lucie-tirand commented
Hello @chris-mvila 

Can you give us this information to enable us to integrate your work?

> Hello :)
> 
> I don't know why it was asked to remove the data needed to test this RP, but in order to integrate this work we will need the output data (anonymized) from the curls commands proposed above (if necessary, you can send them to me by e-mail). Thanks again for your contribution :)

2025-07-10 08:09 UTC, chris-mvila commented
Hello @lucie-tirand 

You will find the requested data in the attached file.
It is the output from the plugin using the --debug option.
The output is identical to that of the curl command.
It is not possible to retrieve data from multiple pages at once using the curl command.

[fortiauthenticator_with_debug_option.txt](https://github.com/user-attachments/files/21156864/fortiauthenticator_with_debug_option.txt)

2026-04-16 09:36 UTC, lucie-tirand commented
Hello :)

Thanks for your contribution 🙏 This PR is handled in the 26.02 release [here](https://github.com/centreon/centreon-plugins/releases/tag/plugins-20260200).

2026-04-16 09:36 UTC, closed without merging