Update uptime.pm
centreon/centreon-plugins pull request #4853
Opened 2024-01-22 08:39 UTC by SavCent

le script affichera le message de temps d'activité de la base de données suivi de la date de démarrage au format "Start time = YYYY/MM/DD HH:mm:ss"

2024-01-23 14:04 UTC, cgagnaire requested changes
Please remove those french comments.

2024-01-23 14:04 UTC, cgagnaire commented on src/database/mysql/mode/uptime.pm
> +    my $msg = sprintf("database is up since %d days", $uptime_days);
Why using a variable ?

2024-01-23 14:04 UTC, cgagnaire commented on src/database/mysql/mode/uptime.pm
> +    $self->{output}->output_add(long_msg => "Start time = $start_time");
Should be added as part of the standard output between brackets.

2024-01-25 21:32 UTC, omercier commented
@SavCent I'm sorry you felt obliged to remove your comments. I was going to ask you to translate them into english since it is better for non-french speaking contributors.

@cgagnaire please don't dissuade other contributors from adding comments to the code. We appreciate comments at Centreon, and our plugins' code lacks a lot of comments to be more easily understood.

2024-01-30 08:00 UTC, SavCent commented
Hi,
so comment are back ;)

2025-04-02 12:05 UTC, Evan-Adam commented
Bonjour @SavCent 
Merci pour cette contribution :heart: 
Pour des raisons techniques interne le code à été intégré dans la pr #5535, dans laquelle j'ai cherry-pick puis squash les commit de cette PR.
Le devrai être disponible lors de la prochaine mise à jour des plugins.
Bonne journée !

--- 
Hello SavCent
Thanks for this contribution :heart: 
For technical reasons the code will be integrated in #5535 , where i cherry-picked and squash commits from here.
It should be available in the next plugin release
Have a good day

2025-04-02 12:05 UTC, closed without merging