[CTOR-304] [Plugin] [InternalPR] New Veeam backup plugin
centreon/centreon-plugins pull request #4886
Opened 2024-02-06 16:30 UTC by lucie-dubrunfaut

## Description

Work in progress
Veeam mode through wsman
From @Top76 development (https://github.com/centreon/centreon-plugins/pull/4417)

EDIT by @omercier
REFS: CTOR-304

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

2024-02-06 16:47 UTC, kduret approved these changes

2024-02-07 16:22 UTC, sc979 approved these changes
LGTM on pipeline part

2024-02-09 10:11 UTC, Evan-Adam submitted a review, later dismissed

2024-02-09 14:20 UTC, sc979 approved these changes

2024-02-09 19:09 UTC, omercier approved these changes

2024-02-12 07:19 UTC, omercier submitted a review, later dismissed

2024-02-12 08:00 UTC, sdepassio submitted a review, later dismissed

2024-02-12 08:26 UTC, sdepassio submitted a review, later dismissed

2024-02-12 08:44 UTC, omercier submitted a review, later dismissed

2024-02-12 09:04 UTC, Evan-Adam approved these changes

2024-02-12 09:29 UTC, kduret requested changes

2024-02-12 09:29 UTC, kduret commented on .github/workflows/perl-cpan-libraries.yml
revert those changes

2024-02-12 09:46 UTC, sdepassio approved these changes

2024-02-12 10:24 UTC, kduret approved these changes

2024-02-12 10:29 UTC, sc979 approved these changes

2024-02-12 10:37 UTC, merged