enh(readme): restructuring the readme file
centreon/centreon-plugins pull request #4907
Opened 2024-02-13 17:16 UTC by omercier

## Description

Giving a link to the development guide and more context in general.

2024-02-14 08:36 UTC, smau-centreon requested changes

2024-02-14 08:36 UTC, smau-centreon commented on README.md
> +* **Application**: Apache, Asterisk, Elasticsearch, Github, Jenkins, Kafka, Nginx, Pfsense, Redis, Tomcat, Varnish,...
```suggestion
* **Application**: Apache, Asterisk, Elasticsearch, Github, Jenkins, Kafka, Nginx, Pfsense, Redis, Tomcat, Varnish, etc.
```

2024-02-14 08:36 UTC, smau-centreon commented on README.md
> +* **Cloud**: AWS, Azure, Docker, Office365, Nutanix, Prometheus,...
```suggestion
* **Cloud**: AWS, Azure, Docker, Office365, Nutanix, Prometheus, etc.
```

2024-02-14 08:36 UTC, smau-centreon commented on README.md
> +* **Databases**: Firebird, Informix, MS SQL, MySQL, Oracle, Postgres, Cassandra
```suggestion
* **Databases**: Firebird, Informix, MS SQL, MySQL, Oracle, Postgres, Cassandra.
```

2024-02-14 08:36 UTC, smau-centreon commented on README.md
> +* **Hardware**: printers (RFC3805), UPS (Powerware, Mge, Standard), Sun Hardware, Cisco UCS, SensorIP, HP Proliant, HP Bladechassis, Dell Openmanage, Dell CMC, Raritan,...
```suggestion
* **Hardware**: printers (RFC3805), UPS (Powerware, Mge, Standard), Sun Hardware, Cisco UCS, SensorIP, HP Proliant, HP Bladechassis, Dell Openmanage, Dell CMC, Raritan, etc.
```

2024-02-14 08:36 UTC, smau-centreon commented on README.md
> +* **Network**: Aruba, Brocade, Bluecoat, Brocade, Checkpoint, Cisco AP/IronPort/ASA/Standard, Extreme, Fortigate, H3C, Hirschmann, HP Procurve, F5 BIG-IP, Juniper, PaloAlto, Redback, Riverbed, Rugged
```suggestion
* **Network**: Aruba, Brocade, Bluecoat, Brocade, Checkpoint, Cisco AP/IronPort/ASA/Standard, Extreme, Fortigate, H3C, Hirschmann, HP Procurve, F5 BIG-IP, Juniper, PaloAlto, Redback, Riverbed, Ruggedcom, Stonesoft, etc.
```

2024-02-14 08:36 UTC, smau-centreon commented on README.md
> +* **Operating systems**: Linux (SNMP, NRPE), Freebsd (SNMP), AIX (SNMP), Solaris (SNMP)...
```suggestion
* **Operating systems**: Linux (SNMP, NRPE), Freebsd (SNMP), AIX (SNMP), Solaris (SNMP), etc.
```

2024-02-14 08:36 UTC, smau-centreon commented on README.md
> +* **Storage**: EMC Clariion, Netapp, Nimble, HP MSA p2000, Dell EqualLogic, Qnap, Panzura, Synology...
```suggestion
* **Storage**: EMC Clariion, Netapp, Nimble, HP MSA p2000, Dell EqualLogic, Qnap, Panzura, Synology, etc.
```

2024-02-14 08:36 UTC, smau-centreon commented on README.md
> +If you encounter a behaviour that is clearly a bug or a regression, you are welcom to submit an [issue](https://github.com/centreon/centreon-plugins/issues). Please be aware that this is an open sour
```suggestion
If you encounter a behaviour that is clearly a bug or a regression, you are welcome to submit an [issue](https://github.com/centreon/centreon-plugins/issues). Please be aware that this is an open source project and that there is no guaranteed response time.
```

2024-02-19 09:21 UTC, smau-centreon approved these changes

2024-02-19 09:33 UTC, lucie-dubrunfaut approved these changes

2024-02-19 12:22 UTC, merged