new(packaging): nokia (formerly alcatel) isam snmp plugin
centreon/centreon-plugins pull request #5087
Opened 2024-06-28 14:22 UTC by omercier

## Description

The plugin has been there for a while but never packaged.

REFS: CTOR-594

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Functionality enhancement or optimization (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## How this pull request can be tested ?

No data for tests right now.

## Checklist

- [x] I have followed the **[coding style guidelines](https://github.com/centreon/centreon-plugins/blob/develop/doc/en/developer/plugins_global.md#5-code-style-guidelines)** provided by Centreon
- [x] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (develop).
- [ ] I have implemented automated tests related to my commits.
- [x] I have reviewed all the help messages in all the .pm files I have modified.
  - [x] All sentences begin with a capital letter.
  - [x] All sentences are terminated by a period.
  - [x] I am able to understand all the help messages, if not, exchange with the PO or TW to rewrite them.

2024-07-01 06:58 UTC, lucie-dubrunfaut commented on packaging/centreon-plugin-Network-Nokia-Isam-Snmp/pkg.json
> +	    "snmp_standard/mode/resources/",
```suggestion
        "snmp_standard/mode/resources/",
```

2024-07-01 07:01 UTC, lucie-dubrunfaut submitted a review, later dismissed

2024-07-01 07:16 UTC, lucie-dubrunfaut approved these changes

2024-07-02 08:17 UTC, Evan-Adam requested changes

2024-07-02 08:17 UTC, Evan-Adam commented on tests/resources/spellcheck/stopwords.t
> +sfp.temperature
Please keep the alphabetical order of the file

2024-07-02 08:17 UTC, Evan-Adam commented on src/network/nokia/isam/snmp/mode/hardware.pm
>  Example: --warning='sfp.temperature,1.1,40'
I don't anderstand this exemple, the regex is 1.1 ? there is no catching group in the regexp ?

2024-07-04 15:55 UTC, omercier commented on src/network/nokia/isam/snmp/mode/hardware.pm
>  Example: --warning='sfp.temperature,1.1,40'
```suggestion
Example: --critical='sfp.temperature,1\.1,40'
```

2024-07-04 15:55 UTC, omercier commented on src/network/nokia/isam/snmp/mode/hardware.pm
> +Define the critical thresholds for 'sfp.temperature', 'cardtemperature' (syntax: type,regexp,threshold).
```suggestion
Define the critical thresholds for an instance of a certain type of sensor.
Syntax: <type>,<regexp>,<threshold>.
Supported types of sensors: 'sfp.temperature', 'cardtemperature'.
Instances are identified by the last two parts of the OID, separated by a period (example: 1.1) and are filtered as a regular expression.
```

2024-07-04 15:55 UTC, omercier commented on src/network/nokia/isam/snmp/mode/hardware.pm
> +Define the warning thresholds for 'sfp.temperature', 'cardtemperature' (syntax: type,regexp,threshold).
```suggestion
Define the warning thresholds for an instance of a certain type of sensor.
Syntax: <type>,<regexp>,<threshold>.
Supported types of sensors: 'sfp.temperature', 'cardtemperature'.
Instances are identified by the last two parts of the OID, separated by a period (example: 1.1) and are filtered as a regular expression.
```

2024-07-04 15:55 UTC, omercier commented on src/network/nokia/isam/snmp/mode/hardware.pm
>  Example: --warning='sfp.temperature,1.1,30'
```suggestion
Example: --warning='sfp.temperature,1\.1,30'
```

2024-07-05 09:12 UTC, lucie-dubrunfaut approved these changes

2024-07-05 12:50 UTC, Evan-Adam approved these changes

2024-07-05 15:53 UTC, tuntoja approved these changes

2024-07-05 15:54 UTC, merged